# Site title and subtitle. This is used in _includes/header.html
title: 'MISO'
subtitle: 'An open-source LIMS for NGS sequencing centres'
miso_flavour: 'OICR' 
miso_colour: 'rgb(56,121,59)'

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/TGAC/miso-lims'


# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/miso-docs-oicr'

# URL to your MISO instance for the training tutorial. This is used in
# _includes/logging_in.md
miso_url: 'http://miso.gsi.oicr.on.ca' 

# Configuration for the sequencer name, platform, and sequencing parameters used
# in sections 3 (libraries) and 4 (sequencing). Make sure these match an
# existing and active sequencer and existing sequencing parameters for your MISO
# instance.
sequencer: 'NB551056'
platform: 'NextSeq 550'
seq_params: 'High 2Ã—151'

# Configuration for inidcating who the MISO administrator is and how to contact
# them
admin: 'GSI'
admin-contact: 'email gsi@oicr.on.ca or file a JIRA ticket in _GSI Common_'

#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
#theme: minima
